### ISSUE TITLE
셀럽 리스트 페이지 mock api 작성

### ISSUE THREAD

**Issue by sihyonn** [Step3-kakao-tech-campus/Team13_FE#103]
##  Description
CelebListPage의 셀럽 목록 조회 기능 모킹 api 작성

## TO DO
- [x] keyword에 따른 검색결과
- [x] 무한스크롤
- [x] 프로필 사진 url
- [x] 셀럽 id
- [x] 셀럽 이름
- [x] 진행 중인 펀딩 수
- [x] 총 펀딩 누적금액
- [x] 팔로워 수
- [x] 팔로워 여부
- [ ] 셀럽 순위 - 펀딩금액 / 팔로워별

## Etc
셀럽 신청에 관해서는 어떤 작업을 하면 좋을까요?

**Comment by j8won** [comment]
신청도 똑같이 mock api를 활용해 api 연결 진행해주시면 좋을 것 같아요~
