### ISSUE TITLE
셀럽신청 mock api 작성

### ISSUE THREAD

**Issue by sihyonn** [Step3-kakao-tech-campus/Team13_FE#106]
##  Description
셀럽신청 모달폼에 대한 mock api 작업. 셀럽 등록요청

## TO DO
POST
- [x] celebId
- [x] celebName
- [x] celebGender
- [x] celebGroup
- [ ] profileImage

## Etc
셀럽 신청 시 이미 등록되어있는 셀럽을 파악하는지요?

**Comment by j8won** [comment]
파악 안 합니다~! 일단 신청하고 관리자가 알아서 거절하는 형태예요
