### ISSUE TITLE
공통 컴포넌트 - 검색바

### ISSUE THREAD

**Issue by j8won** [Step3-kakao-tech-campus/Team13_FE#15]
##  Description
<img width="704" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/75734220/3a1f1e39-bbcc-4ad1-8b35-1aff750ddeca">

펀딩 페이지 및 셀럽 페이지에 들어가는 검색바

## TO DO
- [x] {...props} 활용
- [x] placeholder
- [x] 검색 아이콘
- [x] 검색 버튼

## Etc
검색 버튼 말고 엔터를 클릭할 때도 이벤트가 발생하게 해야 할까요?

**Comment by sihyonn** [comment]
저는 엔터입력해도 발생하면 좋을 것 같습니다

**Comment by j8won** [comment]
> 저는 엔터입력해도 발생하면 좋을 것 같습니다

넵 저도 일단은 enter 이벤트에도 검색될 수 있도록 진행하겠습니다!
