### ISSUE TITLE
공통컴포넌트 - Form

### ISSUE THREAD

**Issue by sihyonn** [Step3-kakao-tech-campus/Team13_FE#16]
### 입력 폼

![613BAAC2-8758-46DD-AAE6-4DDE88398DE9](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/86ce0693-6be6-48f1-b787-ceb2dda63b39) 

![55C597F7-A3B0-4121-9D72-697ABB3469CB_4_5005_c](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/a4e072f9-07b8-4fa2-9dcf-df0f5e82c9e6)

## TO DO
- [ ] validation check(focus-red, error message)
- [ ] palceholder
- [ ] propTypes
- [ ] label

**Comment by j8won** [comment]
해당 이슈는 지금 있는 테스트 페이지 말고 로그인 페이지 새로 생성해서 진행해도 괜찮을 것 같습니다!

**Comment by sihyonn** [comment]
네!
