### ISSUE TITLE
공통컴포넌트 - CelebPageCard

### ISSUE THREAD

**Issue by Klomachenko** [Step3-kakao-tech-campus/Team13_FE#32]
##  Description
![image](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/102893954/ddffcbd6-c318-4b82-a80b-db44355c0788)

- 공통 컴포넌트 CelebPageComponent
  - 이름이 좀 이상해서 CelebPageCard 로 변경하겠습니다.
- 셀럽 페이지
- 궁금한 점
  - 이미 팔로우한 사람의 경우엔 팔로우 버튼이 보이지 않아야 하는건지, 언팔 버튼이 생성되어야 하는건지
## TO DO
- [ ] 이미 팔로우한 사람인 경우 상태관리 정책 정하기
- [ ] hover 시 색상 반전
- [ ] 팔로우 버튼 공통컴포넌트 확인

## Etc
기타 사항

**Comment by j8won** [comment]
해당 컴포넌트는 셀럽 페이지에서만 쓰이지 않나요? 그렇다면 공통 컴포넌트 말고 @/components/celebrity 디렉토리를 생성해서 그 안에서 컴포넌트를 만드는 게 좋을 것 같아요!

그리고 컴포넌트명으오 CelebInfoGridCard 어떨까요?

**Comment by j8won** [comment]
셀럽 페이지는 제가 진행 중인 레이아웃과 겹쳐서 컴포넌트만 진행하면 좋을 것 같아요

**Comment by j8won** [comment]
팔로잉 여부를 true/false로 통신값을 받을 예정입니다 이미 팔로잉 중인 상태면 secondary 타입 버튼으로 텍스트를 팔로우로 변경하는 거 어떨까요

+ 팔로잉 버튼은 다른 컴포넌트에도 쓰이니 공통 컴포넌트로 따로 생성하는 게 어떨까요?

**Comment by j8won** [comment]
hover 색상 반전은 Button 컴포넌트로 이미 구현이 되어있으니 활용하는 것을 추천합니다

**Comment by Klomachenko** [comment]
> 해당 컴포넌트는 셀럽 페이지에서만 쓰이지 않나요? 그렇다면 공통 컴포넌트 말고 @/components/celebrity 디렉토리를 생성해서 그 안에서 컴포넌트를 만드는 게 좋을 것 같아요!
> 
> 그리고 컴포넌트명으로 CelebInfoGridCard 어떨까요?

넵 확인했습니다!
