### ISSUE TITLE
추천 셀럽카드 컴포넌트

### ISSUE THREAD

**Issue by sihyonn** [Step3-kakao-tech-campus/Team13_FE#58]
##  Description
<img width="723" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/765d59a3-a930-4146-9717-5cbbe982946e"> </br>
메인페이지의 추천셀럽 컴포넌트
## TO DO
- [ ] 셀럽이미지, 이름
- [ ] 팔로우 중인 팔로우 숫자
- [ ] 팔로우버튼
- [ ] 추천셀럽 표시개수 : 3

## Etc
이것도 호버시 fundInfoCard 처럼 같은 효과 보여주면 될까요?

**Comment by j8won** [comment]
네 좋아요!! grid 템플릿 안에 있는 애들은 다 호버 스타일링 주면 UI적으로 좋을 것 같습니다 ㅎㅎ
