### ISSUE TITLE
셀럽페이지

### ISSUE THREAD

**Issue by sihyonn** [Step3-kakao-tech-campus/Team13_FE#66]
##  Description
<img width="588" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/c3662656-a9ff-4451-a6e9-378720261d90">

+ 셀럽페이지
+ 펀딩 총액과 팔로워별로 가장 많은 셀럽부터 순위에따라 CelebInfoGridCard 보여주기
+ 상위 1, 2, 3위는 프로필 좌측상단에 해당 등수의 아이콘 붙여주기
+ 우측하단 셀럽신청 버튼 클릭하면 셀럽을 신청할 수 있는 모달 띄어주기

## TO DO
- [x] 캐로셀
- [x] 셀럽검색바
- [x] 순위
   - [x] GridTemplate에 CelebInfoCard 담기
   - [ ] SortButtons(펀딩총액순 | 팔로워순)따라 순위 변경
   - [x] 상위 3위권 프로필 좌측상단 아이콘배치
- [x] 셀럽신청 버튼 - 셀럽신청 작성 모달

## Etc
궁금한점
+ 123등에게 붙여줄 아이콘 혹시 참고할 곳이 있을까요? 아니면 이미지일까요?
+ 셀럽검색바를 통해 검색시 해당 결과는 바로 하단에 띄어지면 되나요?
추가적으로 셀럽신청 모달창은 이슈 새로 생성해서 만들도록 하겠습니다!

**Comment by j8won** [comment]
1. 아이콘은 [https://icons8.com/icons/color](https://icons8.com/icons/color)에서 피그마의 아이콘명 그대로 검색하면 나옵니다
2. 셀럽 검색을 하면 자동으로 `/celebrity?keyword="입력값"`으로 페이지가 이동합니다. 그리고 추후 react-query를 이용해 키워드가 바뀌는 것을 감지해 api 통신을 할 예정입니다. 그러므로 아직은 검색에 대해 생각할 필요는 없어요! 일단 UI 배치만 한다고 생각하면 됩니다!

+ 1, 2, 3 등수 아이콘을 페이지단에서 css로 꾸겨넣는 것보다는 celebInfoGridCard 컴포넌트 내부에 추가하면 좋을 것 같아요

**Comment by sihyonn** [comment]
오옹 참고해서 개발하겠습니다 감사합니다~

**Comment by Klomachenko** [comment]
하단에 나오게 하려면 디바운싱도 적용해야 할 수도 있을텐데

차라리 주원님 말씀대로 일단 UI 배치만 하는 게 좋아보여요!

추후에 같이 논의해봐요!

**Comment by j8won** [comment]
@Klomachenko 키보드 입력할 때마다 페이지 이동하는 게 아니라 키보드에 키워드 입력 후 엔터키 클릭 혹은 검색 버튼 클릭 이벤트 발생시 페이지 이동하는 거라 추후 디바운싱은 적용 안해도 될 것 같아요! ㅎㅎ
