### ISSUE TITLE
셀럽신청(모달)

### ISSUE THREAD

**Issue by sihyonn** [Step3-kakao-tech-campus/Team13_FE#67]
##  Description
<img width="206" alt="image" src="https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/124874266/7833a611-4fd2-4207-b621-cb082ecd516e">

+ 셀럽신청
+ 셀럽페이지 우측하단 셀럽신청 버튼 클릭시 나타나는 모달창의 폼
+ /celebrity/register 

## TO DO
- [ ] 신청할 셀럽 이미지파일 등록
- [ ] 신청할 셀럽 정보 폼
    - [ ] 이름 : 직접입력
    - [ ] 성별 : 남/녀 택
    - [ ] 분류 : 드롭다운 선택. 스포츠, 배우, 가수, sns셀럽?, 저명인사(기타)
    - [ ] 소속그룹 : 드롭다운 선택. 
- [ ] 신청하기 버튼

## Etc
+ 분류와 소속그룹을 어떻게 나누는게 좋을까요?
+ 이름을 제외하고 나머지는 모두 선택으로 가는거죠?

**Comment by j8won** [comment]
@sihyonn 
1. 분류는 아래 자료 + 기타가 될 것 같아요. constant로 관리하면 좋을 것 같습니다.

https://files.slack.com/files-pri/T050DF8AU94-F060K8J26A0/______________2023-10-10_222929.png

2. 소속 그룹만 선택사항이고 나머지는 필수입니다! 근데 이게 이미지 파일이 들어가서 react-hook-form으로 하기 더 어려울 수도 있어요 그래서 저 같은 경우에 펀딩 생성하기 페이지에서 그냥 useState 이용하고 에러 처리는 react.toast 이용했습니다! 참고하시면 좋을 것 같아요 ㅎㅎ
