### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by Klomachenko** [Step3-kakao-tech-campus/Team13_FE#88]
##  Description
![image](https://github.com/Step3-kakao-tech-campus/Team13_FE/assets/102893954/a3e4c232-47d3-473c-be98-e3a8ea74f438)
- 공통 컴포넌트를 활용해 메인 페이지를 생성한다.
- UI 및 페이지 이동
- api 로직은 추후 추가 예정 
## TO DO
- [ ] FundInfoGridCard
- [ ] RecCelebCard
- [ ] Carousel
- [ ] Gnb

## Etc
- 빠트린 공통 컴포넌트가 있다면 댓글로 남겨주시면 감사하겠습니다!
- 라우터의 경우 카드 하나하나마다 다 번호가 다를 텐데 어떻게 적용을 하면 될 까요?
 - `/fund/:fundId` 이걸 이용해야 할 것 같은데 이미 나와있는게 있나요?
-  또 주의해야 할 점이 있다면 댓글 부탁드립니다.

**Comment by j8won** [comment]
1. Gnb와 Carousel의 경우 mainLayout을 활용해 적용시킬 수 있습니다~! 
2. 페이지 이동의 경우 각 카드에 다 적용되어 있어서 그 부분은 신경 안 쓰셔도 됩니다. 각각 카드 컴포넌트에서 어떻게 구현했는지 봐보시면 좋을 것 같아요.
3. 지금 아직 merge 안 된 pr에 마감 임박한 펀딩 조회하는 mock api, api handler, useApi가 있어서, 머지 후에 pull 하고 이 api들 활용해보는 것도 좋을 것 같아요
4. 제가 #87 에서 RecCelebCard 리팩토링을 해서 컴포넌트명이 바뀌었는데 추후 해당 pr 머지 후에 충돌 해결할 때 주의해서 확인해주세요

**Comment by Klomachenko** [comment]
넵 감사합니다! 열심히 진행해볼게요!
